version: '3'

services:
  agent-service:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "8050:8050"
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/library.db
      - TARGET_FOLDER=/app/data
    restart: unless-stopped

  mem0-service:
    image: mcp/mem0
    depends_on:
      - postgres
    ports:
      - "8051:8050"
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mem0
    restart: unless-stopped

volumes:
  postgres-data: 